spring.application.name=keycloak-ms
server.port=8087

keycloak.url=http://keycloak:8080
logging.level.root=INFO
keycloak.realm=Authentication
keycloak.client-id=oauth2-client-login
keycloak.client-secret=L27OruDJ8AdKglAGpwe9DshOB8uyKucz
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web.servlet=DEBUG
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true