spring.application.name=keycloak-ms
server.port=8087

keycloak.url=http://keycloak:8180

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8180/realms/Authentication/protocol/openid-connect/certs

keycloak.realm=Authentication
keycloak.client-id=oauth2-client-login
keycloak.client-secret=8UFbLujf3yDlxdOqDHMD9TWFc6OsA5s4
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web.servlet=DEBUG
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true