version: "3.8"

networks:
  ms-network:
    driver: bridge

volumes:
  mongo-data:
  mysql-data:
  rabbitmq-data:

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ms-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ms-network
    # pas de ports exposés pour éviter conflit

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ms-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8180:8080"
    networks:
      - ms-network

  discovery-server:
    build: ./discovery-server/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ms-network

  product-service:
    build: ./product-service/product-service
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/product-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/microservices-realm
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_VAULT_ENABLED=false
    depends_on:
      - mongodb
      - discovery-server
      - keycloak
    networks:
      - ms-network
  review-service:
    build: ./review-service/review-service
    container_name: review-service
    ports:
      - "3002:3002"
    environment:
      - PRODUCT_SERVICE_HOST=product-service
      - PRODUCT_SERVICE_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - ms-network
    depends_on:
      - product-service


  inventory-service:
    build: ./inventory-service/inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=inventory-service
      - SERVER_PORT=8084
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/inventory-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/microservices-realm
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - SPRING_CLOUD_VAULT_ENABLED=false
    depends_on:
      - mysql-db
      - rabbitmq
      - discovery-server
      - keycloak
    networks:
      - ms-network

  order-service:
    build: ./order-service/order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=order-service
      - SERVER_PORT=8082
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/order_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/microservices-realm
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    depends_on:
      - mysql-db
      - rabbitmq
      - discovery-server
      - keycloak
    networks:
      - ms-network
  chat-service:
    build: ./chat-service/chat-service            # adapte le chemin si besoin
    container_name: chat-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_APPLICATION_NAME=chat-service
      - SERVER_PORT=8089
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      # Ajoute ici d'autres variables (DB, RabbitMQ, etc.) si ton chat‑service en a besoin
    depends_on:
      - discovery-server
    networks:
      - ms-network

  notification-service:
    build: ./notification-service/notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SERVER_PORT=8085
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/microservices-realm
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    depends_on:
      - rabbitmq
      - discovery-server
      - keycloak
    networks:
      - ms-network

  api-gateway-service:
    build: ./api-gateway-service/api-gateway-service
    container_name: api-gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/microservices-realm
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - keycloak
    networks:
      - ms-network
