spring.application.name=chat-service

server.port=8089
# Keycloak (OAuth2 Resource Server)
# Keycloak (OAuth2 Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/Authentication
