# Service Info
spring.application.name=notification-service
server.port=8095

# Database (MySQL/MariaDB)
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/webapp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDB10Dialect

# Eureka Client
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Spring Cloud Stream
spring.cloud.stream.bindings.notificationEventSupplier-in-0.destination=Notification-queue
spring.cloud.stream.default.binder=rabbit

# Logging
logging.level.com.esprit.notificationservice=DEBUG
